
# Main watchlist route to show whats in watchlist
GET http://localhost:8000/watchlist

###

# View one meteor on watchlist
GET http://localhost:8000/watchlist/5e5d90769dd38a3c47bdb851

###

# Delete meteor from watchlist
DELETE http://localhost:8000/watchlist/delete/5e5d90769dd38a3c47bdb851


###

# Add meteor to watchlist
POST http://localhost:8000/watchlist/add
Content-Type: application/json

{
    "name": "Beta",
    "id": 3,
    "nametype": "icy",
    "class": "third class",
    "mass": 6789,
    "fall": false,
    "year": 1567
}

###

# Update meteor from watchlist
PATCH http://localhost:8000/watchlist/edit/5e5d8c89858e063923584223
Content-Type: application/json 

{
  "name": "Trident"
}

###

# View all meteorites in dataset
GET http://localhost:8000/watchlist/all

###

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#AUTH

#sign up get route
http://localhost:8000/sign-up