
GET http://localhost:8000/watchlist

###

POST http://localhost:8000/watchlist/
Content-Type: application/json

{
    "name": "Alpha",
    "id": 1,
    "nametype": "big",
    "class": "first class",
    "mass": 123,
    "fall": true,
    "year": 20000
}